/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/households/{id}/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{id}/members/{memberId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setPin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{id}/members/{memberId}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setCredentials"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{id}/members/{childId}/guardians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setGuardians"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/shopping/lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getList"];
        put: operations["updateList"];
        post?: never;
        delete: operations["deleteList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/recipes/{recipeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/menu/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setSlot"];
        post?: never;
        delete: operations["clearSlot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/chores/{choreId}/recurrence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRecurrence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/calendar/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/automation/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assistant/agents/{agentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_3"];
        post?: never;
        delete: operations["reset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{id}/members/{memberId}/verify-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/shopping/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLists"];
        put?: never;
        post: operations["createList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/shopping/lists/{listId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/shopping/lists/{listId}/clear-purchased": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clearPurchased"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/recipes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/recipes/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/recipes/import/{importId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/recipes/import/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fromUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/notifications/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["subscribe"];
        delete: operations["unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/chores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/calendar/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/calendar/subscriptions/{subscriptionId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/calendar/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importIcs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/automation/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/automation/rules/{ruleId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importHousehold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assistant/agents/{agentId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        patch: operations["updateMember"];
        trace?: never;
    };
    "/api/v1/households/{householdId}/shopping/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeItem"];
        options?: never;
        head?: never;
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/v1/households/{householdId}/chores/{choreId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_4"];
        trace?: never;
    };
    "/api/v1/households/{householdId}/calendar/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch: operations["update_5"];
        trace?: never;
    };
    "/api/v1/notifications/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vapidPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/shopping/lists/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["defaultList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWeek"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/assistant/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribe_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assistant/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providers_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assistant/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{householdId}/recipes/import/{importId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["discard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetRole: {
            /** @enum {string} */
            role: "ADMIN" | "ADULT" | "CHILD";
        };
        MemberDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            name?: string;
            /** @enum {string} */
            role?: "ADMIN" | "ADULT" | "CHILD";
            color?: string;
            /** Format: date-time */
            createdAt?: string;
            username?: string;
            guardianIds?: string[];
            hasPin?: boolean;
            hasCredentials?: boolean;
        };
        SetPin: {
            pin?: string;
        };
        SetCredentials: {
            username: string;
            password: string;
        };
        SetGuardians: {
            guardianIds: string[];
        };
        UpdateList: {
            name: string;
        };
        ShoppingItemDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: double */
            quantity?: number;
            unit?: string;
            category?: string;
            recurring?: boolean;
            done?: boolean;
        };
        ShoppingListDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            name?: string;
            items?: components["schemas"]["ShoppingItemDto"][];
        };
        CreateRecipe: {
            name: string;
            /** Format: int32 */
            servings?: number;
            notes?: string;
            description?: string;
            steps?: string[];
            tags?: string[];
            ingredients?: components["schemas"]["IngredientDto"][];
            imageMimeType?: string;
            imageData?: string;
        };
        IngredientDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: double */
            quantity?: number;
            unit?: string;
            category?: string;
        };
        RecipeDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            name?: string;
            /** Format: int32 */
            servings?: number;
            notes?: string;
            description?: string;
            steps?: string[];
            tags?: string[];
            imageMimeType?: string;
            imageData?: string;
            ingredients?: components["schemas"]["IngredientDto"][];
            /** Format: date-time */
            createdAt?: string;
        };
        SetSlot: {
            /** Format: int32 */
            dayOfWeek: number;
            /** @enum {string} */
            mealType: "BREAKFAST" | "LUNCH" | "SNACK" | "DINNER";
            text?: string;
            /** Format: uuid */
            recipeId?: string;
        };
        MealSlotDto: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            dayOfWeek?: number;
            /** @enum {string} */
            mealType?: "BREAKFAST" | "LUNCH" | "SNACK" | "DINNER";
            text?: string;
            /** Format: uuid */
            recipeId?: string;
        };
        UpdateRecurrence: {
            /** Format: date */
            dueDate?: string;
            /** @enum {string} */
            recurrenceFreq?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            /** Format: int32 */
            recurrenceInterval?: number;
            rotationMemberIds?: string[];
        };
        ChoreDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            title?: string;
            /** Format: uuid */
            assigneeId?: string;
            done?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date */
            dueDate?: string;
            /** @enum {string} */
            recurrenceFreq?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            /** Format: int32 */
            recurrenceInterval?: number;
            rotationMemberIds?: string[];
        };
        UpdateSubscription: {
            name?: string;
            url?: string;
            color?: string;
        };
        CalendarSubscriptionDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            name?: string;
            url?: string;
            color?: string;
            /** Format: date-time */
            lastSyncedAt?: string;
            lastError?: string;
        };
        UpdateRule: {
            enabled?: boolean;
            /** Format: int32 */
            dayOfWeek?: number;
            /** Format: int32 */
            hour?: number;
        };
        AutomationRuleDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            /** @enum {string} */
            type?: "MENU_PROPOSAL" | "SHOPPING_REMINDER";
            enabled?: boolean;
            /** Format: int32 */
            dayOfWeek?: number;
            /** Format: int32 */
            hour?: number;
            /** Format: date-time */
            lastRunAt?: string;
        };
        AgentConfigUpdate: {
            enabled?: boolean;
            provider?: string;
            model?: string;
            /** Format: double */
            temperature?: number;
            /** Format: int32 */
            maxTokens?: number;
        };
        AgentConfigDto: {
            id?: string;
            nameKey?: string;
            descriptionKey?: string;
            supportsMedia?: boolean;
            orchestrator?: boolean;
            enabled?: boolean;
            provider?: string;
            model?: string;
            /** Format: double */
            temperature?: number;
            /** Format: int32 */
            maxTokens?: number;
            defaults?: components["schemas"]["ModelDefaults"];
            overridden?: boolean;
            available?: boolean;
        };
        ModelDefaults: {
            provider?: string;
            model?: string;
            /** Format: double */
            temperature?: number;
            /** Format: int32 */
            maxTokens?: number;
        };
        SetupRequest: {
            householdName: string;
            locale?: string;
            timezone?: string;
            memberName: string;
            username: string;
            password: string;
        };
        CreateHousehold: {
            name: string;
            locale: string;
            timezone: string;
        };
        HouseholdDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            locale?: string;
            timezone?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateMember: {
            name: string;
            /** @enum {string} */
            role?: "ADMIN" | "ADULT" | "CHILD";
            color?: string;
            pin?: string;
            username?: string;
            password?: string;
        };
        CreateList: {
            name: string;
        };
        AddItem: {
            name: string;
            /** Format: double */
            quantity?: number;
            unit?: string;
            category?: string;
            recurring?: boolean;
        };
        FilterCondition: components["schemas"]["FilterNode"] & {
            field?: string;
            /** @enum {string} */
            operator?: "EQ" | "NE" | "GT" | "GTE" | "LT" | "LTE" | "LIKE" | "IN" | "BETWEEN" | "IS_NULL" | "IS_NOT_NULL" | "JSON_CONTAINS" | "JSON_CONTAINED_BY" | "JSON_EXISTS" | "JSON_EXISTS_ANY" | "JSON_EXISTS_ALL" | "JSON_PATH_EQ" | "JSON_PATH_LIKE" | "JSON_ARRAY_CONTAINS" | "JSON_ARRAY_CONTAINS_ALL" | "JSON_ARRAY_CONTAINS_ANY";
            value?: unknown;
            values?: unknown[];
        };
        FilterGroup: components["schemas"]["FilterNode"] & {
            /** @enum {string} */
            combinator?: "AND" | "OR";
            filters?: (components["schemas"]["FilterCondition"] | components["schemas"]["FilterGroup"])[];
            and?: (components["schemas"]["FilterCondition"] | components["schemas"]["FilterGroup"])[];
            or?: (components["schemas"]["FilterCondition"] | components["schemas"]["FilterGroup"])[];
        };
        FilterNode: unknown;
        FilterRequest: {
            filter: components["schemas"]["FilterCondition"] | components["schemas"]["FilterGroup"];
        };
        RecipePageDto: {
            content?: components["schemas"]["RecipeDto"][];
            /** Format: int64 */
            totalHits?: number;
            hasMore?: boolean;
        };
        CandidateInfo: {
            key?: string;
            title?: string;
            snippet?: string;
            structured?: boolean;
        };
        ImportSessionInfo: {
            /** Format: uuid */
            id?: string;
            source?: string;
            candidates?: components["schemas"]["CandidateInfo"][];
            aiAvailable?: boolean;
        };
        ConfirmImport: {
            candidates: string[];
        };
        ImportFailure: {
            key?: string;
            title?: string;
            reason?: string;
        };
        ImportOutcome: {
            imported?: components["schemas"]["RecipeDto"][];
            failures?: components["schemas"]["ImportFailure"][];
        };
        UrlImport: {
            url: string;
        };
        PushKeys: {
            p256dh: string;
            auth: string;
        };
        SubscribeRequest: {
            endpoint: string;
            keys?: components["schemas"]["PushKeys"];
        };
        CreateChore: {
            title: string;
            /** Format: uuid */
            assigneeId?: string;
            /** Format: date */
            dueDate?: string;
            /** @enum {string} */
            recurrenceFreq?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            /** Format: int32 */
            recurrenceInterval?: number;
            rotationMemberIds?: string[];
        };
        CreateEvent: {
            title: string;
            /** Format: date */
            date: string;
            time?: string;
            /** Format: int32 */
            durationMinutes?: number;
            /** Format: uuid */
            addedBy?: string;
            assigneeIds?: string[];
            /** @enum {string} */
            recurrenceFreq?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            /** Format: int32 */
            recurrenceInterval?: number;
            /** Format: date */
            recurrenceUntil?: string;
        };
        CalendarEventDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            title?: string;
            /** Format: date */
            date?: string;
            /** Format: date */
            anchorDate?: string;
            time?: string;
            /** Format: int32 */
            durationMinutes?: number;
            /** Format: uuid */
            addedBy?: string;
            assigneeIds?: string[];
            /** @enum {string} */
            recurrenceFreq?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            /** Format: int32 */
            recurrenceInterval?: number;
            /** Format: date */
            recurrenceUntil?: string;
            /** @enum {string} */
            source?: "LOCAL" | "ICS";
            /** Format: uuid */
            subscriptionId?: string;
        };
        CreateSubscription: {
            name: string;
            url: string;
            color?: string;
        };
        ImportResult: {
            /** Format: int32 */
            imported?: number;
        };
        CreateRule: {
            /** @enum {string} */
            type: "MENU_PROPOSAL" | "SHOPPING_REMINDER";
            /** Format: int32 */
            dayOfWeek: number;
            /** Format: int32 */
            hour: number;
        };
        AgentRequest: {
            agentId?: string;
            conversationId?: string;
            message?: string;
            attachments?: components["schemas"]["Attachment"][];
            /** Format: uuid */
            memberId?: string;
        };
        Attachment: {
            mimeType?: string;
            data?: string;
        };
        AgentResponse: {
            agentId?: string;
            conversationId?: string;
            text?: string;
            toolCalls?: string[];
            delegations?: components["schemas"]["Delegation"][];
        };
        Delegation: {
            agentId?: string;
            text?: string;
            /** Format: int64 */
            latencyMs?: number;
        };
        HouseholdExport: {
            household?: components["schemas"]["HouseholdDto"];
            members?: components["schemas"]["MemberDto"][];
            mealPlans?: components["schemas"]["MealPlanDto"][];
            shoppingLists?: components["schemas"]["ShoppingListDto"][];
            calendarEvents?: components["schemas"]["CalendarEventDto"][];
            chores?: components["schemas"]["ChoreDto"][];
            automationRules?: components["schemas"]["AutomationRuleDto"][];
            calendarSubscriptions?: components["schemas"]["CalendarSubscriptionDto"][];
        };
        MealPlanDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            householdId?: string;
            /** Format: int32 */
            isoYear?: number;
            /** Format: int32 */
            isoWeek?: number;
            slots?: components["schemas"]["MealSlotDto"][];
        };
        AgentTestResult: {
            ok?: boolean;
            /** Format: int64 */
            latencyMs?: number;
            text?: string;
            error?: string;
        };
        UpdateMember: {
            name?: string;
            color?: string;
        };
        UpdateItem: {
            name?: string;
            /** Format: double */
            quantity?: number;
            unit?: string;
            category?: string;
            recurring?: boolean;
            done?: boolean;
        };
        UpdateChore: {
            title?: string;
            /** Format: uuid */
            assigneeId?: string;
            done?: boolean;
        };
        UpdateEvent: {
            title?: string;
            /** Format: date */
            date?: string;
            time?: string;
            /** Format: int32 */
            durationMinutes?: number;
            assigneeIds?: string[];
            /** @enum {string} */
            recurrenceFreq?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            /** Format: int32 */
            recurrenceInterval?: number;
            /** Format: date */
            recurrenceUntil?: string;
        };
        SetupStatus: {
            required?: boolean;
        };
        MeDto: {
            kind?: string;
            member?: components["schemas"]["MemberDto"];
            household?: components["schemas"]["HouseholdDto"];
        };
        AgentDefinition: {
            id?: string;
            nameKey?: string;
            descriptionKey?: string;
            supportsMedia?: boolean;
            toolNames?: string[];
            toolDescription?: string;
            orchestrator?: boolean;
            model?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        ProviderDto: {
            provider?: string;
            available?: boolean;
            models?: string[];
            error?: string;
        };
        UnsubscribeRequest: {
            endpoint: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRole"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"];
                };
            };
        };
    };
    setPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPin"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"];
                };
            };
        };
    };
    setCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCredentials"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"];
                };
            };
        };
    };
    setGuardians: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                childId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetGuardians"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"];
                };
            };
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    updateList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateList"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    deleteList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                recipeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                recipeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipe"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                recipeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setSlot: {
        parameters: {
            query: {
                year: number;
                week: number;
            };
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSlot"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MealSlotDto"];
                };
            };
        };
    };
    clearSlot: {
        parameters: {
            query: {
                year: number;
                week: number;
                dayOfWeek: number;
                mealType: "BREAKFAST" | "LUNCH" | "SNACK" | "DINNER";
            };
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRecurrence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                choreId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurrence"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChoreDto"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscription"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendarSubscriptionDto"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRule"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AutomationRuleDto"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentConfigDto"];
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseholdDto"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHousehold"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"][];
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMember"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"];
                };
            };
        };
    };
    verifyPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPin"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    listLists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoppingListDto"][];
                };
            };
        };
    };
    createList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateList"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItem"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoppingItemDto"];
                };
            };
        };
    };
    clearPurchased: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipe"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                tag?: string;
                ingredient?: string;
                page?: number;
                size?: number;
                sort?: string;
                direction?: string;
            };
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FilterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipePageDto"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportSessionInfo"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                importId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmImport"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportOutcome"];
                };
            };
        };
    };
    fromUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlImport"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportSessionInfo"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChoreDto"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChore"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChoreDto"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendarEventDto"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvent"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendarEventDto"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendarSubscriptionDto"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscription"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendarSubscriptionDto"];
                };
            };
        };
    };
    sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendarSubscriptionDto"];
                };
            };
        };
    };
    importIcs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/calendar": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportResult"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AutomationRuleDto"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRule"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AutomationRuleDto"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AutomationRuleDto"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    importHousehold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseholdExport"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentTestResult"];
                };
            };
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMember"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberDto"];
                };
            };
        };
    };
    removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoppingItemDto"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                choreId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                choreId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChore"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChoreDto"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEvent"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendarEventDto"];
                };
            };
        };
    };
    vapidPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeDto"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    defaultList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    getWeek: {
        parameters: {
            query: {
                year: number;
                week: number;
            };
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MealPlanDto"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseholdExport"];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentDefinition"][];
                };
            };
        };
    };
    subscribe_1: {
        parameters: {
            query: {
                household: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    }[];
                };
            };
        };
    };
    providers_1: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProviderDto"][];
                };
            };
        };
    };
    agents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentConfigDto"][];
                };
            };
        };
    };
    discard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                householdId: string;
                importId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
