ALTER TABLE shopping_item ADD COLUMN quantity DOUBLE PRECISION;
ALTER TABLE shopping_item ADD COLUMN unit VARCHAR(50);
ALTER TABLE shopping_item ADD COLUMN category VARCHAR(100);
ALTER TABLE shopping_item ADD COLUMN recurring BOOLEAN NOT NULL DEFAULT FALSE;
